---
- name: add distribution-specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: add Debian Wheezy workaround
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
  when: (ansible_distribution == "Debian") and (ansible_distribution_release == "wheezy")

- name: install powermgmt-base
  apt:
    pkg:
    state: present
    cache_valid_time: "{{ unattended_cache_valid_time }}"
    update_cache: yes
  when: unattended_only_on_ac_power

- name: install unattended-upgrades
  apt:
    pkg: unattended-upgrades
    state: present
    cache_valid_time: "{{ unattended_cache_valid_time }}"
    update_cache: yes

- name: install reboot dependencies
  include: reboot.yml
  when: unattended_automatic_reboot|bool

- name: create APT auto-upgrades configuration
  template:
    src: auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644

- name: create unattended-upgrades configuration
  template:
    src: unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644

- name: ensure /etc/systemd/system/apt-daily.timer.d exists
  file:
    path: /etc/systemd/system/apt-daily.timer.d
    state: directory

- name: ensure /etc/systemd/system/apt-daily-upgrade.timer.d exists
  file:
    path: /etc/systemd/system/apt-daily-upgrade.timer.d
    state: directory

- name: Change the apt-daily timer
  template:
    src: apt-daily.j2
    dest: /etc/systemd/system/apt-daily.timer.d/override.conf
    owner: root
    group: root
    mode: 0644

- name: Change the apt-daily-upgrade timer
  template:
    src: apt-daily-upgrade.j2
    dest: /etc/systemd/system/apt-daily-upgrade.timer.d/override.conf
    owner: root
    group: root
    mode: 0644

- name: Reload systemd daemon
  systemd:
    daemon_reload: true

- name: Restart apt-daily.timer
  systemd:
    name: apt-daily.timer
    state: restarted
    enabled: true

- name: Restart apt-daily-upgrade.timer
  systemd:
    name: apt-daily-upgrade.timer
    state: restarted
    enabled: true
